### ISSUE TITLE
Mac Compilation

### ISSUE THREAD

**Issue by Rudis1261** [signal11/hidapi#184]
Hi There,

I am trying to compile the code on Mac according to the documentation however I get the following output:
- make: **\* No targets specified and no makefile found.  Stop.

I am not a pro at compiling C, but from what I remember and was able to Google, most people recommend running ./Configure prior to compilation.

Can you give me any other advise?

Kind regards,
Rudi

**Comment by hoosierEE** [comment]
I'm getting the same error after following the instructions from [here](http://www.signal11.us/oss/hidapi/):

> Mac OS X: 
> Change to the mac/ directory and run make. 

What did you have to do in order to build this?
Thanks,
Alex

**Comment by signal11** [comment]
See the README. It's quite detailed. Make sure you're on the latest HEAD from git.

./configure && make && make install

**Comment by hoosierEE** [comment]
Ah, this explains my problem:
```
$ /configure && make && make install
[...]
configure: error: HIDAPI is not supported on your operating system yet
```

I'm on OSX 10.10.4 (14E46).

**Comment by signal11** [comment]
Strange. Must be an autotools issue. Did you ./bootstrap ? I don't have time to work it out right now. Maybe you can see if a newer version of autotools will help.

**Comment by hoosierEE** [comment]
I `./bootstrap`'ed and got this:

```
mac/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
mac/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
mac/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
mac/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
mac/Makefile.am:1:   its definition is in aclocal's search path.
```

I've not yet edited `configure.ac` to see if that helps.  I'm also pressed for time, but hope to come back to this someday.  Sorry that's all I can contribute at the moment!

**Comment by mrpippy** [comment]
I tried compiling the latest HEAD yesterday on 10.10.4 and it worked. I have homebrew installed though, and I think its libtool/autotools was being used.
