### ISSUE TITLE
Windows: hid_write randomly hangs

### ISSUE THREAD

**Issue by amullins83** [signal11/hidapi#198]
Sometimes my application hangs on a call to `hid_write`. This usually occurs after several hundred writes and reads have already completed successfully. Once the application is hung, I can terminate it through the debugger or the task manager, but the device remains non-communicative until it is unplugged from the PC. Resetting the device doesn't seem to help. Any thoughts on what might cause this?

**Comment by amullins83** [comment]
I totally forgot this was still open. Of course the problem was on our device. The input buffer on the device would sometimes get hung up. I forget what the actual source of the problem was because we fixed it over a year ago now. The fix was to have the device send a couple of empty "flush" packets at the end of each actual message. Weird, but it worked.

**Comment by androjes** [comment]
Get_feature or Set_feature randomly return error after many calls.
I know it's may be a device issue, but how can I ensure that is not from hidapi ?

**Comment by signal11** [comment]
By testing, debugging, and troubleshooting :)

Not sure what you want here.... Maybe get a hardware analyzer and check it out. Put some breakpoints in your firmware. Stuff like that...

It's hard for me to debug your hardware from here. Do you have a specific question?

**Comment by tresf** [comment]
> It's hard for me to debug your hardware from here

Slightly off-topic, but I've used a library called [`VirtualHere`](https://www.virtualhere.com/usb_client_software) for this and it works awesome.   Not sure if it'll expose the same issues, but wanted to drop that note.

**Comment by androjes** [comment]
I'm using 2 HID devices, both are based on STM32F4.
Then I need to call infinitely get_feature_report() each 200ms, using non-blocking mode to avoid bad surprise.
And sometimes it returns an error (result < 0) one 1 device.
I notice you that our firmware is already debug and everything seems working perfectly :)

My questions:
1- Does hidapi supports multiple devices without any hidden bug?
2- When I call hid_close() on one device. Does it impact other devices ?
3- How can I ensure if device is physically removed? Is there any better solution than hid_enumerate?

Thank you @signal11 for precious help

**Comment by signal11** [comment]
> 1- Does hidapi supports multiple devices without any hidden bug?

Yes. Multiple devices can be open.

> 2- When I call hid_close() on one device. Does it impact other devices ?

No.

> 3- How can I ensure if device is physically removed? Is there any better solution than hid_enumerate?

hid_read() will return -1.
