### ISSUE TITLE
Sharing mode on windows

### ISSUE THREAD

**Issue by storzinc** [signal11/hidapi#232]
Currently on windows hid devices is opened with FILE_SHARE_READ sharing mode:
https://github.com/signal11/hidapi/blob/master/windows/hid.c#L227
I think it should be FILE_SHARE_READ|FILE_SHARE_WRITE to be consistent with linux, where O_RDWR is used.

**Comment by matlo** [comment]
O_RDWR actually means "Open for reading and writing.".

**Comment by storzinc** [comment]
Ah, you are right, there is no problems with sharing mode.
