### ISSUE TITLE
Use libusb calls for hid_write() ?

### ISSUE THREAD

**Issue by rytz2k** [signal11/hidapi#243]
Greetings:

I'm doing development work on an existing USB device configuration utility that uses both HIDAPI and libusb calls (depending on firmware versions of the device).  libusb calls are "usb_control_msg()" and HIDAPI calls are "hid_write()".

The device is not bluetooth.

Question:  would it be possible to migrate the HIDAPI hid_write() calls to usb_control_msg() calls?  I would like to migrate the code into requiring just a single library.

My understanding thus far is that libusb does not support interfacing with bluetooth devices and that HIDAPI is a wrapper for hidraw or libusb, depending on what type of API is required (HID/non-HID).

Thanks.

**Comment by signal11** [comment]
I'm not entirely sure what the point of that would be, but you can hack it up any way you see fit. To your last paragraph, look at the code. There are two different implementations on Linux. Pick the one that works for you.

**Comment by rytz2k** [comment]
Thanks for the response and info.  I was in the preliminary stages of understanding the various USB libraries and their roles.  Definitely a silly question :)

**Comment by NicoHood** [comment]
@signal11 maybe you should close questions like that if they are answered and dont contain a real issue. That would clean the github issue tracker some more.

**Comment by signal11** [comment]
I typically let the asker close it.

**Comment by NicoHood** [comment]
But this makes the issue tracker very unclear. You should close all invalid issues. And as said, some PRs are really worth and simple to merge. If you could clean up some issues and PRs that'd be nice.
