### ISSUE TITLE
USB Keyboard/Raw device - /dev/input/eventX vanishes when hid_open() is called.

### ISSUE THREAD

**Issue by woehrl** [signal11/hidapi#271]
Hope you could give me a hint. We use a combinated USB HID device for keyboard usage and other reports with Qt 5.5 on a Raspberry Pi 3 (using Raspbian).
Problem is - The keyboard device (dev/input/event0) gets disconnected as soon as I open the hid_device with:
`hid_device *deviceHandle = hid_open(RPIBASE_VENDORID, RPIBASE_PRODUCTID, NULL); `

When the app is started the device is connected and Qt grabs it:
`qt.qpa.input: Opening keyboard at "/dev/input/event0"`

But as soon as we open (hid_open) or send reports (hid_write) with hidapi to the same device, the keyboard just gets disconnected (/dev/input/event0 really vanishes) and Qt disconnects, too:
```
qt.qpa.input: Removing keyboard at "/dev/input/event0"
qt.qpa.input: Unload current keymap and restore built-in
evdevkeyboard: Failed to query led states
qt.qpa.input: switchLed 0 false
qt.qpa.input: switchLed 1 false
qt.qpa.input: switchLed 2 false
```

I would expect a complaint by hidapi or the kernel over concurrent access or so but nothing is found in dmeg/message when that happens...

Interestingly this happens with any keyboard device - not just with that special device we integrated. And the mouse device (e.g. event1) that was attached to the same device path stays alive.

This is the dmesg output:
```
[    3.007392] usb 1-1.4.4: new full-speed USB device number 9 using dwc_otg
[    3.119431] usb 1-1.4.4: New USB device found, idVendor=04d8, idProduct=f1cf
[    3.119459] usb 1-1.4.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.119474] usb 1-1.4.4: Product: My Interface
[    3.119486] usb 1-1.4.4: Manufacturer: My Company
[    3.125260] input: My Company My Interface as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4.4/1-1.4.4:1.0/0003:04D8:F1CF.0001/input/input0
[    3.177871] hid-generic 0003:04D8:F1CF.0001: input,hiddev0,hidraw0: USB HID v1.11 Keyboard [My Company My Interface] on usb-3f980000.usb-1.4.4/input0
```
Anyone a clue?

**Comment by woehrl** [comment]
After having a conversation with Alan and Scott I realized, that I used the hidapi-libusb implementation. After switching and linking to the hidapi-hidraw implementation it runs fine:
`LIBS += -lhidapi-hidraw`
Thanks!

**Comment by NicoHood** [comment]
@woehrl Just a quick question:
I am currently using `libhidapi` from the ubuntu repositories (Installed `libhidapi*`).
However my program doees not find `#include <hidapi.h>`. I used `-lhidapi-hidraw` or `-lhidapi` as gcc flag. `-lusb` for using libusb works though.

Do you know what I am doing wrong? I (preferred) do not want a local copy of hidapi, i'd rather use the built in package.

**Comment by woehrl** [comment]
Did you install package `libhidapi-dev`? And for the right platform? (on ubuntu there might be `libhidapi-dev` and `libhidapi-dev:i386`)...
Then you should have a "hidraw.h" header file on your system - normally in /usr/include/linux/ (you may find it with `locate hidraw.h`. To compile you need a header file - for distribution, the library is sufficient.
You might need to add this include path then to your Makefile.

**Comment by NicoHood** [comment]
```
libhidapi-dev is already the newest version.
libhidapi-hidraw0 is already the newest version.
libhidapi-hidraw0-dbg is already the newest version.
libhidapi-libusb0 is already the newest version.
libhidapi-libusb0-dbg is already the newest version.
```

It is inside `/usr/include/linux/hidraw.h`
I though I can just pass `lhidapi` to the compiler like with libusb. Isn't there such a shortcut?

**Comment by woehrl** [comment]
I never tried on ubuntu, but that is standard linking procedure. Try to add:
```
INCLUDEPATH += /usr/include/linux/
LIBS += -L"/usr/lib/x86_64-linux-gnu/" -lhidapi-hidraw
```
There might also be a way to use pkgconfig, but you might have to google on this...
Good luck, best regards!

**Comment by signal11** [comment]
or better, use pkg-config

**Comment by NicoHood** [comment]
Maybe with more details? I could not find any information about this online.

**Comment by signal11** [comment]
> I could not find any information about this online.

Google yields:
  https://en.wikipedia.org/wiki/Pkg-config
  https://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by woehrl** [comment]
That is exactly what pkgconfig tells you, right:
`$ pkg-config --libs --cflags hidapi-hidraw`
-> `-I/usr/include/hidapi -lhidapi-hidraw`
Use it in your compile statement:
`$ gcc -o test test.c $(pkg-config --libs --cflags hidapi-hidraw)`
(from wikipedia)
