### ISSUE TITLE
hid_get_manufacturer_string and friends fail with large buffers in win32.

### ISSUE THREAD

**Issue by dontech** [signal11/hidapi#278]
Hello hidapi,

Thanks for a great and simple library.

I found the follow more or less by accident:

If hid_get_manufacturer_string(),hid_get_product_string() or hid_get_serial_number_string() is called with a buffer that is larger than 0xFFF wchars then they fail on win32.

First i assumed a bug in hidapi, but found out its a bug in HidD_GetManufacturerString(). Calling that with a buffer that is larger then 0xFFF*2 (it has length in bytes) causes the same problem.

This causes a problem in hidapi, as it makes code that works in e.g. Linux to not work in win32. As HID string cannot be that long anyway, i suggest capping these functions to 0xFFF wchars.

That would make this work the same on all targets, and would make this problem go away.

Thanks,

/pedro

**Comment by signal11** [comment]
Closed with #279
