### ISSUE TITLE
after long time it's unable to open device

### ISSUE THREAD

**Issue by AnCruise** [signal11/hidapi#319]
hi, I'v used the lib in MFC to control a finger device. At the beginning it works well ,but I stop it after the  hid_write() and hid_read() running 11 millions times (by Bus Hound),  and then open device again, it reports 'unable to open device'. Is there something wrong? thanks!

![image](https://cloud.githubusercontent.com/assets/16432733/24279998/5a853c4e-1088-11e7-860d-e3d1ace56759.png)
![image](https://cloud.githubusercontent.com/assets/16432733/24280015/73d5be44-1088-11e7-99aa-b108c2ed46e4.png)
another function uses these code:
![image](https://cloud.githubusercontent.com/assets/16432733/24279971/30676662-1088-11e7-96ee-083300edeee6.png)

**Comment by signal11** [comment]
Looks like you closed this yourself....

For what it's worth:
hid_enumerate() is not necessary in your case where you use hid_open().

Only call hid_init() once at the beginning of execution, not every time you open a device. Unless you're in some kind of multithreaded environment, you don't need to call it at all actually.

You say USB_BULK_BUFF, but it's not actually a bulk endpoint. It's an interrupt endpoint.

Alan.

**Comment by AnCruise** [comment]
Thanks for your help , Alan .
I have resolved the problem . Yes , I used it in a multithreaded environment , so every time it is necessary to call it . And the USB_BULK_BUFF is a number I have defined , it is causing you to misunderstand , sorry.
William.

**Comment by signal11** [comment]
It's harmful to call it every time, and will introduce a race condition. Call it once at the beginning of execution.
