### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by ghost** [signal11/hidapi#413]
I'm sorry, but I don't know how to use this. I'm just getting linker command failures when I place the sample cpp file given in the same directory as the header file and then compile using g++.

Another issue is that test gui is damaged and I can't run this.

Can you explain how to use this api?

**Comment by nonchip** [comment]
try reading the readme.

**Comment by buaabyl** [comment]
Is there any compile or link error log?

**Comment by nonchip** [comment]
@buaabyl well the first compile error seemed to be "using g++" instead of running make ;)

**Comment by buaabyl** [comment]
the core library `hid.c` is c file, but `hidtest.cpp` is c++ file, you may using g++ to compile them all. or gcc for `hid.c` and `g++` for `hidtest.cpp`, and link them together.

**Comment by nonchip** [comment]
true, you can, but it's not really how you should link this lib according to the readme :P

so probably better trying the makefile to prevent "layer 8" issues, and of course pasting the log on error, as you already said.

**Comment by ghost** [comment]
Yes, I was trying to compile them all, but with some linker issues. It's ok, I found the hidtest file which is very helpful, thank you.
