### ISSUE TITLE
hid_read hang in linux, but hid_write and hid_read work fine in window10

### ISSUE THREAD

**Issue by Rockyhoon** [signal11/hidapi#459]
I've tried both libusb/hid.c and linux/hid.c, when I run hidtest.cpp, it hangs on at hid_read(), if I 	hid_set_nonblocking(handle, 0). And I've set device permission by the method provided in /udev directory. The whole system works fine in window10. Now I am desperate.
Any suggestion is appreciated!

**Comment by Youw** [comment]
NOTE: #373 

Suggest to close in favor of https://github.com/libusb/hidapi/issues/170

**Comment by Rockyhoon** [comment]
OK, I've already post on that repo
