### ISSUE TITLE
Windows version doesn't enumerate devices when exactly one is connected

### ISSUE THREAD

**Issue by jm4R** [signal11/hidapi#466]
I don't know if this is coincidence, but this is my case:

I plug UPS HID device (CyberPower or APC) as an only HID device in the whole system, and `hid_enumerate` returns `nullptr`.

When I plug USB keyboard as a second device, `hid_enumerate` enumerates both - keyboard and UPS.

On Linux and exactly the same machine it works fine.

**Comment by Youw** [comment]
Please see #373

**Comment by jm4R** [comment]
@Youw yes, I am aware of that, just miss-googled the right repo. Thanks!

**Comment by Youw** [comment]
right, I sueggest to close the ticket here
