### ISSUE TITLE
hid_write failed

### ISSUE THREAD

**Issue by arilink** [signal11/hidapi#471]
I used Hidapi to create a project for two-way communication with HID, now I can read the messages sent from the device to the computer normally and can use Bughound to send data to the device, but when I try to call hid_write to send a message to the device it returns the value Always -1 Failed to send my device's report ID is 1. I also set the first bit of the data packet to 1, but I still can't send data successfully. Why?

**Comment by Youw** [comment]
Please see #468 and close this ticket, if you may.

**Comment by arilink** [comment]
This question is sloved , thankyou
